# key는 32byte (256bit)이상.
jwt:
  secretKey: 12346789012346789012346789012345 # 이 키를 이용하여 암호화를 할때 사용한다.
  refreshKey: 12346789012346789012346789012345

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/examplesdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Rdbckr69173+
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
